name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Change this to 'master' if your main branch is named master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add build steps here if you are using React/Vue/Flutter
      # Example:
      # - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUX_FITNESS_APP }}'
          channelId: live
          projectId: flux-fitness-app
